/*
 * DEPRECATED — unused stub page.
 *
 * This file is auto-generated by Wix for every page that exists in the
 * Wix Editor. The corresponding "SIGNUP - Special Event" page currently
 * has no UI and no implementation; it shipped as default Velo
 * boilerplate.
 *
 * To fully retire this page:
 *   1. Open the Wix Editor → Pages → delete "SIGNUP - Special Event".
 *   2. Run `npx wix pull` (or re-publish) — this file will disappear
 *      locally on its own.
 *   3. Remove any menu links that pointed to the page.
 *
 * Until the Wix Editor deletion happens, this file stays in the repo as
 * a no-op with an explicit marker so it doesn't get mistaken for
 * in-progress work.
 *
 * Tracked in docs/BACKLOG.md → Signup Forms.
 */

$w.onReady(function () {
    // Intentionally empty. See deprecation note above.
});
